#!/bin/bash

# Clear Browser Cache Helper Script
echo "================================"
echo "Browser Cache Clear Instructions"
echo "================================"
echo ""
echo "If you're still seeing Anthropic errors, your browser has cached the old settings."
echo ""
echo "Follow these steps:"
echo ""
echo "1. Chrome/Edge:"
echo "   - Press Ctrl+Shift+Delete"
echo "   - Select 'Cached images and files'"
echo "   - Click 'Clear data'"
echo "   - Or: F12 → Application → Clear storage"
echo ""
echo "2. Firefox:"
echo "   - Press Ctrl+Shift+Delete"
echo "   - Select 'Cache'"
echo "   - Click 'Clear Now'"
echo "   - Or: Ctrl+Shift+K (Clear All Data)"
echo ""
echo "3. Safari:"
echo "   - Press Cmd+Option+E"
echo "   - Develop → Empty Caches"
echo ""
echo "4. Alternative (Quickest):"
echo "   - Open in Incognito/Private window"
echo "   - This bypasses cache"
echo ""
echo "After clearing cache:"
echo "   1. Refresh the page (Ctrl+R or Cmd+R)"
echo "   2. Check Settings → Provider should be 'OpenAI'"
echo "   3. If not, manually select OpenAI and save"
echo ""
echo "================================"